export const bigCreditData = {
   credit: [
      {
         title: 'Пополнения оборотных средств',
         sum: 'до 300 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 3-х лет',
         description: false,
      },
      {
         title: 'Овердрафт',
         sum: 'до 200 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 2-х лет',
         description: false,
      },
      {
         title: 'Инвестиционный кредит',
         sum: 'до 200 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 10 лет',
         description: true,
         pageId: 1,
      },
      {
         title: 'Рефинансирование',
         sum: 'до 250 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 3-х лет',
         description: false,
      },
      {
         title: 'Кредит под залог недвижимости',
         sum: 'до 100 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 10 лет',
         description: false,
      },
      {
         title: 'Льготное кредитование по программе МСП',
         sum: 'до 300 млн ₽',
         payment: '4%-27% годовых',
         // deadline: 'до 15 лет',
         description: false,
      },
      {
         title: 'Кредит на исполнение контракта',
         sum: 'до 500 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 3-х лет',
         description: false,
      },
      {
         title: 'Банковская гарантия',
         sum: 'от 50 млн до 3 млрд ₽',
         payment: '4%-27% годовых',
         deadline: 'до 60 месяцев',
         description: true,
         pageId: 2,
      },
      {
         title: 'Факторинг',
         sum: 'до 300 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'бессрочно',
         description: true,
         pageId: 3,
      },
      {
         title: 'Проектное финансирование',
         sum: 'до 3 млрд ₽',
         payment: '4%-27% годовых',
         deadline: 'до 60 месяцев',
         description: true,
         pageId: 4,
      },
      {
         title: 'Облигационные займы',
         sum: 'до 3 млрд ₽',
         payment: '4%-27% годовых',
         deadline: 'до 60 месяцев',
         description: true,
         pageId: 5,
      },
   ],
};
