export const smallCreditData = {
   credits: [
      {
         title: 'Кредит для развития бизнеса',
         sum: 'до 300 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 5 лет',
         description: true,
         pageId: 1,
      },
      {
         title: 'Займ для бизнеса',
         sum: 'до 30 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 12 месяц',
         description: true,
         pageId: 2,
      },
      {
         title: 'Кредит для ИП',
         sum: 'до 100 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 10 лет',
         description: true,
         pageId: 3,
      },
      {
         title: 'Оборотный кредит',
         sum: 'до 500 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 5 лет',
         description: true,
         pageId: 4,
      },
      {
         title: 'Кредит на исполнение госконтракта',
         sum: 'до 150 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 3-х лет',
         description: true,
         pageId: 5,
      },
      {
         title: 'Тендерный кредит/займ',
         sum: 'до 150 млн ₽',
         payment: '4%-27% в месяц',
         deadline: 'до 5 лет',
         description: true,
         pageId: 6,
      },
      {
         title: 'Овердрафт',
         sum: 'до 30 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 2-х лет',
         description: true,
         pageId: 7,
      },
      {
         title: 'Бизнес Ипотека',
         sum: 'до 300 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 15 лет',
         description: true,
         pageId: 8,
      },
      {
         title: 'Потребительский кредит',
         sum: 'до 100 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 30 лет',
         description: true,
         pageId: 9,
      },
      {
         title: 'Кредит под залог недвижимости',
         sum: 'до 300 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 15 лет',
         description: true,
         pageId: 10,
      },
      {
         title: 'Кредит под залог автотранспорта',
         sum: 'до 15 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 7 лет',
         description: true,
         pageId: 11,
      },
      {
         title: 'Льготное кредитование для бизнеса',
         sum: 'до 100 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 24 месяцев',
         description: true,
         pageId: 12,
      },
      {
         title: 'Банковская гарантия',
         sum: 'до 500 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 5 лет',
         description: true,
         pageId: 13,
      },
      {
         title: 'Факторинг',
         sum: 'до 300 млн ₽',
         payment: '4%-27% в месяц',
         deadline: 'бессрочно',
         description: true,
         pageId: 14,
      },
      {
         title: 'Лизинг',
         sum: 'до 300 млн ₽',
         payment: 'аванс от 0%',
         deadline: 'до 7 лет',
         description: true,
         pageId: 15,
      },
      {
         title: 'Кредит для поставщиков маркетплейсов',
         sum: 'до 50 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 5 лет',
         description: true,
         pageId: 16,
      },
      {
         title: 'Кредит без залога',
         sum: 'до 10 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 7 лет',
         description: true,
         pageId: 17,
      },
      {
         title: 'Экспресс кредит на оборудование',
         sum: 'до 1 млн ₽',
         payment: '4%-27% годовых',
         deadline: 'до 5 лет',
         description: true,
         pageId: 18,
      },
   ],
};
